### PR TITLE
Creation of quote component

### LINKED ISSUE #16: create quote component in landing page
get a random quote from `quote.json` file .  and render that in landing page

### PR DESCRIPTION
**Pull request by iagormoraes**
## Description
Closes  [issue #16](https://github.com/IshankaDSenevirathne/EduEra/issues/16)

This PR implement the feature of quote component with random quotes rendered dynamically once per page load.

### CODE REVIEW

**Comment by RizkyRajitha** [comment]
hi @iagormoraes ,
you did great , 

just get the `quote.json` from https://github.com/IshankaDSenevirathne/EduEra/blob/dev/src/paperdata/quotes.json

you might need to change the branch to `dev` for this and submit pr to `dev` branch as well . (new pr also fine )

thanks for you contribution 🙌 .

**Review by RizkyRajitha — CHANGES_REQUESTED** [review]
use 
https://github.com/IshankaDSenevirathne/EduEra/blob/dev/src/paperdata/quotes.json

**Comment by iagormoraes** [comment]
> use
> https://github.com/IshankaDSenevirathne/EduEra/blob/dev/src/paperdata/quotes.json

Sure, I'll do the changes

**Review by RizkyRajitha — APPROVED** [review]

**Comment by RizkyRajitha** [comment]
@iagormoraes Awesome work.

thanks for your contribution 🙌 .

**Pull request merged**
